// Build script for Render deployment
// Generates config.js from environment variables set in Render dashboard
const fs = require('fs');

const config = `// Auto-generated by build.js — DO NOT edit manually
const firebaseConfig = {
    apiKey: "${process.env.VITE_FIREBASE_API_KEY || 'MISSING_API_KEY'}",
    authDomain: "${process.env.VITE_FIREBASE_AUTH_DOMAIN || 'MISSING_AUTH_DOMAIN'}",
    projectId: "${process.env.VITE_FIREBASE_PROJECT_ID || 'MISSING_PROJECT_ID'}",
    storageBucket: "${process.env.VITE_FIREBASE_STORAGE_BUCKET || 'MISSING_STORAGE_BUCKET'}",
    messagingSenderId: "${process.env.VITE_FIREBASE_MESSAGING_SENDER_ID || 'MISSING_SENDER_ID'}",
    appId: "${process.env.VITE_FIREBASE_APP_ID || 'MISSING_APP_ID'}"
};

const appId = '${process.env.VITE_APP_ID || 'default-app-id'}';

export { firebaseConfig, appId };
`;

fs.writeFileSync('config.js', config);
console.log('✅ config.js generated successfully from environment variables');
